version: '3.7'

services:
  db:
    container_name: diet_helper__db
    image: postgres:12.4
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: diet_helper__db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - diet_helper__network

  storage:
    container_name: diet_helper__storage
    image: bitnami/minio:latest
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=12345678
      - MINIO_DEFAULT_BUCKETS=diet-helper
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - storage_data:/data
    networks:
      - diet_helper__network

volumes:
  db_data:
  storage_data:

networks:
  diet_helper__network:
    driver: bridge
